schema: mechcore.unit
type_name: farseer
unit_type_id: 26

formation:
  members: 1
  slot_size: 30
  footprint: {width: 30, depth: 30}

domain: ground
max_life: 11991
collision_radius: 11
move_speed: 16
rotate_speed: 60
has_body: true
independent_aim: false
rvo: {outer_radius: 10, inner_radius: 6, size: l, collider_priority: 7, priority: 0.2}

attack:
  base_damage: 1348
  min_range: 0
  range: 125
  attack_half_angle: 60
  targets: {ground: true, air: true}
  lock_target: true
  quick_switch_target: true
  timing:
    interval: 2
    interval_offset: 0
    initial_cooldown: 0
    prepare: 0
    attack_point: 0
    backswing: 0
    cooling: 0
  splash_radius: 8
  weapons:
    mode: normal
    indices: [0]
    per_skill: 1
  melee: false
  path:
    type: projectile
    count: 2
    release_interval: 0.2
    speed: 140
    target_offset_radius: 5
    evenly_allocate_targets: false
    extra_search_range: 0
    pre_flight_height: 60
    simulated_motion: false
    interceptible: true
    max_life: 126360
