schema: mechcore.unit
type_name: marksman
unit_type_id: 2

formation:
  members: 1
  slot_size: 20
  footprint: {width: 20, depth: 20}

domain: ground
max_life: 1622
collision_radius: 8
move_speed: 8
rotate_speed: 70
has_body: true
independent_aim: false
rvo: {outer_radius: 8, inner_radius: 4, size: l, collider_priority: 6, priority: 0.006}

attack:
  base_damage: 2329
  min_range: 0
  range: 140
  attack_half_angle: 20
  targets: {ground: true, air: true}
  lock_target: true
  quick_switch_target: true
  timing:
    interval: 3.1
    interval_offset: 0.6
    initial_cooldown: 0
    prepare: 0.5
    attack_point: 0.1
    backswing: 0
    cooling: 0.2
  splash_radius: 0
  weapons:
    mode: normal
    count: 1
    per_skill: 1
  path:
    type: projectile
    count: 1
    release_interval: 0.2
    speed: 500
    target_offset_radius: 0
    evenly_allocate_targets: false
    extra_search_range: 0
    pre_flight_height: 0
    simulated_motion: false
    interceptible: false
    max_life: 0
