schema: mechcore.training_ground
buildings:
  - team_id: 0
    building_type_id: 1
    position: {x: -140, z: -170}
    life: 3400
    radius: 10
    collision_enabled: true
  - team_id: 0
    building_type_id: 2
    position: {x: 140, z: -170}
    life: 3400
    radius: 10
    collision_enabled: true
  - team_id: 1
    building_type_id: 2
    position: {x: -140, z: 170}
    life: 3400
    radius: 10
    collision_enabled: true
  - team_id: 1
    building_type_id: 1
    position: {x: 140, z: 170}
    life: 3400
    radius: 10
    collision_enabled: true
