schema: mechcore.unit_prices

units:
  - type: fortress
    unit_id: 1
    supply: 400
    members: 1
    unlock_supply: 200
    upgrade_supply: 200
  - type: marksman
    unit_id: 2
    supply: 100
    members: 1
    upgrade_supply: 50
  - type: vulcan
    unit_id: 3
    supply: 400
    members: 1
    unlock_supply: 200
    upgrade_supply: 200
  - type: melting_point
    unit_id: 4
    supply: 400
    members: 1
    unlock_supply: 200
    upgrade_supply: 200
  - type: rhino
    unit_id: 5
    supply: 200
    members: 1
    unlock_supply: 50
    upgrade_supply: 100
  - type: wasp
    unit_id: 6
    supply: 200
    members: 12
    unlock_supply: 50
    upgrade_supply: 100
  - type: mustang
    unit_id: 7
    supply: 200
    members: 12
    upgrade_supply: 100
  - type: steel_ball
    unit_id: 8
    supply: 200
    members: 4
    upgrade_supply: 100
  - type: fang
    unit_id: 9
    supply: 100
    members: 18
    upgrade_supply: 50
  - type: crawler
    unit_id: 10
    supply: 100
    members: 24
    upgrade_supply: 50
  - type: overlord
    unit_id: 11
    supply: 500
    members: 1
    unlock_supply: 200
    upgrade_supply: 250
  - type: stormcaller
    unit_id: 12
    supply: 200
    members: 4
    unlock_supply: 50
    upgrade_supply: 100
  - type: sledgehammer
    unit_id: 13
    supply: 200
    members: 5
    upgrade_supply: 100
  - type: hacker
    unit_id: 14
    supply: 200
    members: 1
    unlock_supply: 100
    upgrade_supply: 100
  - type: arclight
    unit_id: 15
    supply: 100
    members: 1
    upgrade_supply: 50
  - type: phoenix
    unit_id: 16
    supply: 200
    members: 2
    unlock_supply: 50
    upgrade_supply: 100
  - type: war_factory
    unit_id: 17
    supply: 800
    members: 1
    unlock_supply: 350
    upgrade_supply: 400
  - type: wraith
    unit_id: 18
    supply: 300
    members: 1
    unlock_supply: 50
    upgrade_supply: 150
  - type: scorpion
    unit_id: 19
    supply: 300
    members: 1
    unlock_supply: 50
    upgrade_supply: 150
  - type: fire_badger
    unit_id: 20
    supply: 200
    members: 3
    upgrade_supply: 100
  - type: sabertooth
    unit_id: 21
    supply: 200
    members: 1
    upgrade_supply: 100
  - type: typhoon
    unit_id: 22
    supply: 300
    members: 2
    unlock_supply: 50
    upgrade_supply: 150
  - type: sandworm
    unit_id: 23
    supply: 400
    members: 1
    unlock_supply: 200
    upgrade_supply: 200
  - type: tarantula
    unit_id: 24
    supply: 200
    members: 1
    upgrade_supply: 100
  - type: phantom_ray
    unit_id: 25
    supply: 200
    members: 3
    unlock_supply: 50
    upgrade_supply: 100
  - type: farseer
    unit_id: 26
    supply: 300
    members: 1
    unlock_supply: 50
    upgrade_supply: 150
  - type: raiden
    unit_id: 27
    supply: 400
    members: 1
    unlock_supply: 200
    upgrade_supply: 200
  - type: hound
    unit_id: 28
    supply: 100
    members: 5
    upgrade_supply: 50
  - type: abyss
    unit_id: 29
    supply: 800
    members: 1
    unlock_supply: 350
    upgrade_supply: 400
  - type: void_eye
    unit_id: 30
    supply: 100
    members: 3
    upgrade_supply: 50
  - type: vortex
    unit_id: 31
    supply: 100
    members: 1
    upgrade_supply: 50
  - type: centurion
    unit_id: 32
    supply: 300
    members: 1
    unlock_supply: 50
    upgrade_supply: 150
  - type: mountain
    unit_id: 2002
    supply: 800
    members: 1
    unlock_supply: 350
    upgrade_supply: 400
