"""The build's data, as `scripts/decompile.py` exports it, for the extract scripts.

Every `scripts/extract*.py` reads the game's tables through this module and
nothing else: no path id, no hand-written field parser, no build number of
its own. The build is `config/config.yaml`'s `game_build` unless a script is
given `--build`, and its export is `work/decomp/<build>/`, which
`scripts/decomp.py sync` fetches and `scripts/decompile.py` makes.

    container()            ConfigDataContainer.m_Structure
    level0("Class")        the m_Structure of a level0 data object, e.g. MechSkillGroupData
    shared("Class")        {name: m_Structure} of a class sharedassets0 holds, e.g. MapLayout
    names("Table")         {row id: {"en": ..., "zh": ...}} from the configuration's localization
    in_standard(row)       whether a row can appear outside Interstellar Expedition
"""

import argparse
import functools
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DECOMP = ROOT / "work" / "decomp"
# `limitedScene` values that are Interstellar Expedition (`matchSettings` with
# `serverSubType` 8 and 9). mechcore models no scene of that mode.
EXPEDITION_SCENES = {8, 9}


def configured_build():
    text = (ROOT / "config" / "config.yaml").read_text()
    match = re.search(r"^game_build:\s*(\S+)", text, re.M)
    if not match:
        sys.exit("config/config.yaml names no game_build")
    return match.group(1)


def arguments(description, extra=None):
    """Parse `--build` and whatever else a script adds; select the build."""
    parser = argparse.ArgumentParser(description=description,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--build", default=None, help="a build under work/decomp; config/config.yaml's by default")
    if extra:
        extra(parser)
    parsed = parser.parse_args()
    select(parsed.build or configured_build())
    return parsed


_build = None


def select(build):
    global _build
    directory = DECOMP / build
    if not (directory / "config-data-container.json").exists():
        sys.exit(
            f"no export of build {build} under {DECOMP}; run "
            f"`scripts/decomp.py sync --build {build}`, or `scripts/decompile.py` on the machine with the game"
        )
    _build = build
    _load.cache_clear()


def build():
    if _build is None:
        select(configured_build())
    return _build


@functools.cache
def _load(relative):
    path = DECOMP / build() / relative
    if not path.exists():
        sys.exit(f"build {build()} has no {relative}; rerun `scripts/decompile.py --force config`")
    return json.loads(path.read_text())


def container():
    return _load("config-data-container.json")["m_Structure"]


def level0(name):
    return _load(f"level0/{name}.json")["m_Structure"]


def shared(name):
    directory = DECOMP / build() / "sharedassets0" / name
    if directory.is_dir():
        return {path.stem: _load(f"sharedassets0/{name}/{path.name}")["m_Structure"]
                for path in sorted(directory.glob("*.json"))}
    return {name: _load(f"sharedassets0/{name}.json")["m_Structure"]}


@functools.cache
def _terms():
    source = _load("resources/LanguageSourceAsset.json")["m_Structure"]["mSource"]
    languages = [language["Name"] for language in source["mLanguages"]]
    english, chinese = languages.index("English"), languages.index("简体中文")
    return {term["Term"]: (term["Languages"][english], term["Languages"][chinese]) for term in source["mTerms"]}


def names(table):
    """The official English and Simplified Chinese name of every row of a config table."""
    prefix = f"ConfigData/{table}/name_"
    return {
        int(term[len(prefix):]): {"en": english, "zh": chinese}
        for term, (english, chinese) in _terms().items()
        if term.startswith(prefix) and term[len(prefix):].isdigit()
    }


def in_standard(row):
    """A row limited to Expedition scenes only is not part of any mode mechcore models."""
    scenes = row.get("limitedScene")
    return not scenes or not set(scenes) <= EXPEDITION_SCENES


def header(generator):
    """The first lines of a generated config file."""
    return [f"# Build {build()}. Generated by {generator}; do not edit by hand."]
