#!/usr/bin/env python3
"""Extract the standard 1v1 reinforcement prediction inputs into `config/reinforcements.yaml`.

    python3 scripts/extract_reinforcements.py [--build BUILD]

Reads the build through `scripts/build_data.py`: the commander skill and
equipment cards of `CommanderSkillGroupData` and `EquipmentGroupData`, the
officers, unit cards, round pools and level weights of `ConfigDataContainer`,
and `Config.reinforceItemCount`.
"""
import json
from pathlib import Path
import sys

import build_data
from extract_opening import eligible
from extract_prices import config_numbers, group_rows


def catalogue(group, kind):
    return [dict(row, kind=kind) for row in group_rows(group).values()
            if 'scope' in row and 100_000 <= row['id'] < 100_000_000]


def extract(structure):
    rows = catalogue('CommanderSkillGroupData', 'skill') + catalogue('EquipmentGroupData', 'equipment')
    rows.extend(dict(row, kind='officer') for row in structure['officerDatas'])
    cards = {}
    for row in rows:
        if row['scope'] != 1 or not eligible(row):
            continue
        # EAppearCondition: 0 none, 1 NonexistUnit (offered only while the
        # side holds none of `unitID`), 2 SupplyPercent (offered only while
        # `unitID` holds a share of every player's investment inside
        # `appearConditionParameter`, in percent).
        condition = row.get('appearCondition', 0)
        assert condition in (0, 1, 2)
        card = dict(level=row['level'], group=row.get('typeID', 0),
                    earliest=row['earliestRound'], latest=row['latestRound'],
                    repeated=row['canRepeated'],
                    cooldown=row['kind'] == 'skill' and row['level'] == 4,
                    absent_units=row.get('unitID', []) if condition == 1 else [])
        if condition == 2:
            low, high = row['appearConditionParameter']
            card['supply_share'] = dict(low=low, high=high, units=row['unitID'])
        cards[row['id']] = card
    units = {}
    for row in structure['unitReinforceDatas']:
        if not eligible(row):
            continue
        assert row['scope'] == 0 and len(set(row['unitID'])) == 1
        units[row['id']] = dict(unit=row['unitID'][0], round=row['activeRound'])
    # decline_supply[i] is what declining the unit offer of rounds[i] pays.
    pools = {row['id']: dict(rounds=row['roundGroup'], decline_supply=row['giveUpSupply'],
                             supply_round=row['supplyRound'],
                             supplies=row['supplyReinforceID'])
             for row in structure['unitReinforceRoundPool'] if eligible(row)}
    weights = {row['round']: [row[f'level{level}'] for level in range(1, 6)]
               for row in structure['reinforceItemProbabilityDatas']}
    prevented = {row['id']: row['unitID'] for row in structure['officerDatas']
                 if row['preventUnitReinforcements'] and eligible(row)}
    # A level costs its unit's mechExpDatas row, looked up by mechID; every
    # standard row charges one price for all eight levels.
    levels = {row['id']: row for row in structure['mechExpDatas']}
    unit_costs = {}
    for row in structure['cardDatas']:
        if not build_data.in_standard(row):
            continue
        level = levels[row['mechID']]
        upgrades = {level[f'upgradeSupplyLv{at}'] for at in range(2, 10)}
        assert len(upgrades) == 1, f"unit {row['id']} upgrades at {sorted(upgrades)}"
        unit_costs[row['id']] = dict(supply=row['baseMoney'], unlock=row['unlockPrice'],
                                     upgrade=upgrades.pop(),
                                     tech_step=row['techUpgradeIncreaseSupplyPerCount'],
                                     tech_cap=row['techUpgradeMaxSupplyLimit'])
    quantity = int(next(row['value'] for row in structure['commonParms']
                        if row['key'] == 'unit_reinforcement_quantity'))
    return dict(ordinary_count=config_numbers(structure)['reinforce_item_count'],
                unit_count=quantity, cards=dict(sorted(cards.items())),
                units=dict(sorted(units.items())), pools=pools, weights=weights,
                prevented=prevented, unit_costs=unit_costs)


def main():
    build_data.arguments(__doc__)
    inputs = extract(build_data.container())
    lines = ['# Standard versus 1v1. Generated by',
             '# scripts/extract_reinforcements.py; see docs/rules/reinforcements.md.', '']
    for key, value in inputs.items():
        if isinstance(value, dict):
            lines.append(f'{key}:')
            lines.extend(f'  {identifier}: {json.dumps(row)}' for identifier, row in value.items())
        else:
            lines.append(f'{key}: {value}')
        lines.append('')
    (Path(__file__).resolve().parents[1] / 'config/reinforcements.yaml').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
