#!/usr/bin/env python3
"""Extract build 2259's standard 1v1 initialization inputs.

Usage: python scripts/extract_opening.py <ConfigDataContainer.json> <Data/>
Requires UnityPy. Writes config/opening.yaml; IDs preserve native sort order.
"""
import collections
import json
from pathlib import Path
import struct
import sys

from extract_prices import blobs, monobehaviour_body, read_string

MAPS = (1001, 1011, 1021, 1031, 1032)


def extract(structure, data):
    # MapData name -> layoutName. In this build the supported maps share the
    # serialized MapLayout at sharedassets0.assets path ID 243676.
    raw = blobs(data / 'sharedassets0.assets', [243656, 243657, 243659, 243676])
    layouts = {}
    for path_id in (243656, 243657, 243659):
        name, _ = read_string(raw[path_id], 28)
        body = monobehaviour_body(raw[path_id])
        _, at = read_string(body, 0)  # baseName
        layout, _ = read_string(body, at)
        layouts[name.decode()] = layout
    layout_name, _ = read_string(raw[243676], 28)
    body = monobehaviour_body(raw[243676])
    assert struct.unpack_from('<i', body)[0] == 2
    at, centers = 4, []
    for seat in range(2):
        custom, x, y, player, main, count = struct.unpack_from('<6i', body, at)
        assert (custom, x, y, player, count) == (0, 0, 0, 0, 3)
        at += 24
        for _ in range(count):
            region, x, y, width, height, facing, _, _, _ = struct.unpack_from('<9i', body, at)
            at += 36
            if region == main:
                assert facing == seat * 2
                # Red's document frame rotates the world by half a turn.
                sign = 1 if seat == 0 else -1
                centers.append({'x': sign * (x + width // 2), 'y': sign * (y + height // 2)})
    assert at == len(body) and len(centers) == 2

    groups = collections.defaultdict(list)
    for row in structure['officerDatas']:
        if row['scope'] == 1 and eligible(row) and row['typeID'] > 0:
            groups[row['typeID']].append(row['id'])
    # Opening specialists have no grouped variants and draw nothing in setup.
    assert all(row['typeID'] == 0 for row in structure['officerDatas'] if row['scope'] == 2 and eligible(row))
    maps = {}
    for row in structure['matchSettings']:
        if row['id'] in MAPS:
            assert layouts[row['mapData']] == layout_name
            assert row['advanceSameUnitMaximum'] == 3
            maps[row['id']] = {
                'groups': row['constructionGroupID'],
                'centers': centers,
                # One reactor core per seat, or one every seat shares.
                'reactor_cores': row['reactorCores'],
            }
    wanted = {group for row in maps.values() for group in row['groups']}
    constructions = {}
    for row in structure['constructionGroupDatas']:
        if row['id'] not in wanted:
            continue
        assert not row['isOnlyMirrorSymmetry'] and row['canReverseHorizontal'] and not row['isCompact']
        units = json.loads(row['datas'])
        assert all(not unit['isRotate'] for unit in units)
        constructions[row['id']] = [
            {'unit': unit['unitID'], 'position': {axis: unit['position'][axis] for axis in ('x', 'y')}}
            for unit in units
        ]
    return {
        'officer_groups': {key: sorted(value) for key, value in sorted(groups.items())},
        'unit_round_pools': sorted(row['id'] for row in structure['unitReinforceRoundPool'] if eligible(row)),
        'maps': maps,
        'constructions': constructions,
    }


def eligible(row):
    return not row['limitedScene'] or 1 in row['limitedScene']


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    structure = json.loads(Path(sys.argv[1]).read_text())['m_Structure']
    result = extract(structure, Path(sys.argv[2]))
    lines = ['# Build 1.11.1.3.2259, standard versus 1v1. Generated by',
             '# scripts/extract_opening.py; see docs/rules/opening.md.', '']
    for key, value in result.items():
        if isinstance(value, dict):
            lines.append(f'{key}:')
            lines.extend(f'  {identifier}: {json.dumps(row, separators=(", ", ": "))}' for identifier, row in value.items())
        else:
            lines.append(f'{key}: {json.dumps(value)}')
        lines.append('')
    (Path(__file__).resolve().parents[1] / 'config/opening.yaml').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
