#!/usr/bin/env python3
"""Extract the map's towers, their strengthening and their loss into `config/towers.yaml`.

    python3 scripts/extract-towers.py [--build BUILD] [--check]

Read through `scripts/build_data.py`:

* `buildings`: the four towers of the map the Training Ground plays on,
  `matchSettings` row `TRAINING_GROUND`. Its `mapData` names a `MapData` whose
  `buildingDatas` place every building; the towers are the ones a team owns,
  in the map's order, which is the order `BuildingManager.buildings` gives a
  side's towers. A tower's life is not the map's: `CrystalElement` takes the
  `towerDefaultDatas` row whose `limitedScene` holds the match's
  `serverSubType` (`CheckSceneLimit(int subType)`).
* `levels`: level 0 is that `towerDefaultDatas` row, whose `destroyAddBuff`
  names the buff its loss writes; levels 1 to 4 are `towerStrengthenDatas`,
  each adding its `life` on top of the levels below and naming a buff.
* `destroyed_buff`: the `buffDatas` rows the levels name, which are one buff
  but for `duration`; the script refuses them if they are not.

Rates and durations are the FPoint raw integers the build stores, with a
comment reading each one. `docs/rules/towers.md` states what they mean.
"""

import pathlib
import sys

import build_data

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "config/towers.yaml"
TRAINING_GROUND = 1021
ONE = 1 << 32
# The fields that may differ between the five rows. Everything else is the
# one buff, and has to agree.
PER_ROW = {"id", "duration", "name"}


def raw(value):
    return value["m_rawValue"] if isinstance(value, dict) else value


def reading(value):
    text = f"{value / ONE:+.4f}".rstrip("0").rstrip(".")
    return f"  # {text}"


def metres(value):
    quotient, remainder = divmod(raw(value), ONE)
    if remainder:
        raise SystemExit(f"a tower sits at a fraction of a metre: {raw(value)}")
    return quotient


def tower_default(structure, sub_type):
    rows = [row for row in structure["towerDefaultDatas"] if sub_type in row["limitedScene"]]
    if len(rows) != 1:
        raise SystemExit(f"{len(rows)} towerDefaultDatas rows hold scene {sub_type}")
    return rows[0]


def render(structure):
    setting = next(row for row in structure["matchSettings"] if row["id"] == TRAINING_GROUND)
    default = tower_default(structure, setting["serverSubType"])
    map_data = build_data.shared("MapData")[setting["mapData"]]
    towers = [row for row in map_data["buildingDatas"] if row["teamType"] >= 0]
    if sorted((row["teamType"], row["buildingType"]) for row in towers) != [(0, 1), (0, 2), (1, 1), (1, 2)]:
        raise SystemExit(f"{setting['mapData']} does not place one tower of each type per team")

    buffs = {row["id"]: row for row in structure["buffDatas"]}
    levels = sorted((row for row in structure["towerStrengthenDatas"] if build_data.in_standard(row)),
                    key=lambda row: row["level"])
    if [row["level"] for row in levels] != [1, 2, 3, 4]:
        raise SystemExit("towerStrengthenDatas does not hold levels 1 to 4 outside Expedition")
    named = [default["destroyAddBuff"]] + [row["buffID"] for row in levels]
    rows = [buffs[buff] for buff in named]
    first = rows[0]
    for row in rows[1:]:
        differs = {
            key for key in set(first) | set(row)
            if key not in PER_ROW and raw(first.get(key)) != raw(row.get(key))
        }
        if differs:
            raise SystemExit(f"buff {row['id']} differs from buff {first['id']} in {sorted(differs)}")
    for row in rows:
        if raw(row["duration"]) % ONE:
            raise SystemExit(f"buff {row['id']} lasts a fraction of a second")

    lines = [
        "schema: mechcore.towers",
        "",
        "# The map's towers, what strengthening one does and what losing one",
        "# writes on its side. Generated by scripts/extract-towers.py;",
        "# docs/rules/towers.md states what each field means. A rate is an",
        "# FPoint Q32.32 raw integer: -3865470566 is -0.9.",
        "",
        f"# The four towers of {setting['mapData']}, the Training Ground's map:",
        "# team, building type (1 the Energy Tower, 2 the Research Center),",
        "# centre in metres, life from towerDefaultDatas, half-width.",
        "buildings:",
    ]
    for tower in towers:
        lines += [
            f"  - team_id: {tower['teamType']}",
            f"    building_type_id: {tower['buildingType']}",
            f"    position: {{x: {metres(tower['position']['x'])}, z: {metres(tower['position']['y'])}}}",
            f"    life: {default['life']}",
            f"    radius: {metres(tower['radius'])}",
            f"    collision_enabled: {str(tower['enablePathfinding']).lower()}",
        ]
    lines += [
        "",
        "# The buff a tower's loss writes, one buff that differs by level only",
        "# in how long it lasts.",
        "destroyed_buff:",
        f"  name: {first['name']}",
        f"  buff_divide: {first['buffDivide']}",
        f"  additive: {str(first['isAdditiveMode']).lower()}",
        f"  max_additive_stack: {first['maxAdditiveStack']}",
        f"  can_affect_construction: {str(first['canAffectConstruction']).lower()}",
        f"  clear_when_technologies_disabled: {str(first['isClearSelfBuffWhenDisableTech']).lower()}",
        f"  move_speed_rate: {raw(first['speedChangeRate'])}{reading(raw(first['speedChangeRate']))}",
        f"  damage_rate: {raw(first['damageChangeRate'])}{reading(raw(first['damageChangeRate']))}",
        f"  amplify_damage_rate: {raw(first['amplifyDamageRate'])}{reading(raw(first['amplifyDamageRate']))}",
    ]
    if "canAffectTower" in first:
        lines.append(f"  can_affect_tower: {str(first['canAffectTower']).lower()}")
    lines += [
        "",
        "# One row per strengthen level. `life` is what the level adds to the",
        "# tower, on top of the levels below it; `buff` is the buffDatas row its",
        "# loss writes, and `duration` that row's, in seconds.",
        "levels:",
    ]
    lives = [0] + [row["life"] for row in levels]
    for level, (life, row) in enumerate(zip(lives, rows)):
        lines.append(
            f"  - {{level: {level}, life: {life}, buff: {row['id']}, duration: {raw(row['duration']) // ONE}}}"
        )
    return "\n".join(lines) + "\n"


def main():
    arguments = build_data.arguments(__doc__, lambda parser: parser.add_argument("--check", action="store_true"))
    written = render(build_data.container())
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != written:
            print("config/towers.yaml differs from the build's export", file=sys.stderr)
            return 1
        print("config/towers.yaml agrees with the build's export byte for byte")
        return 0
    OUTPUT.write_text(written)
    print(f"towers of build {build_data.build()} -> {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
