#!/usr/bin/env python3
"""Extract the standard 1v1 initialization inputs into `config/opening.yaml`.

    python3 scripts/extract_opening.py [--build BUILD]

Reads the build through `scripts/build_data.py`: `matchSettings` for the maps,
each map's `MapData.layoutName` and that `MapLayout`'s player territories for
the two seats' centres, the officer groups, the unit reinforcement round
pools and the constructions a map places. IDs preserve native sort order.
"""
import collections
import json
from pathlib import Path
import sys

import build_data

MAPS = (1001, 1011, 1021, 1031, 1032)


def seat_centres(layout):
    """Each seat's main region's centre, red's in its own frame (the world turned half a turn)."""
    territories = layout['playerTerritories']
    assert len(territories) == 2
    centers = []
    for seat, territory in enumerate(territories):
        assert not territory['useCustomStartPosition'] and territory['startPosition'] == {'x': 0, 'y': 0}
        main = [region for region in territory['regions'] if region['id'] == territory['mainRegionID']]
        assert len(main) == 1 and main[0]['facing'] == seat * 2
        rect = main[0]['bound']['rect']
        sign = 1 if seat == 0 else -1
        centers.append({'x': sign * (rect['m_XMin'] + rect['m_Width'] // 2),
                        'y': sign * (rect['m_YMin'] + rect['m_Height'] // 2)})
    return centers


def extract(structure):
    map_data = build_data.shared('MapData')
    layouts = build_data.shared('MapLayout')
    groups = collections.defaultdict(list)
    for row in structure['officerDatas']:
        if row['scope'] == 1 and eligible(row) and row['typeID'] > 0:
            groups[row['typeID']].append(row['id'])
    # Opening specialists have no grouped variants and draw nothing in setup.
    assert all(row['typeID'] == 0 for row in structure['officerDatas'] if row['scope'] == 2 and eligible(row))
    maps = {}
    for row in structure['matchSettings']:
        if row['id'] in MAPS:
            assert row['advanceSameUnitMaximum'] == 3
            maps[row['id']] = {
                'groups': row['constructionGroupID'],
                'centers': seat_centres(layouts[map_data[row['mapData']]['layoutName']]),
                # One reactor core per seat, or one every seat shares.
                'reactor_cores': row['reactorCores'],
            }
    wanted = {group for row in maps.values() for group in row['groups']}
    constructions = {}
    for row in structure['constructionGroupDatas']:
        if row['id'] not in wanted:
            continue
        assert not row['isOnlyMirrorSymmetry'] and row['canReverseHorizontal'] and not row['isCompact']
        units = json.loads(row['datas'])
        assert all(not unit['isRotate'] for unit in units)
        constructions[row['id']] = [
            {'unit': unit['unitID'], 'position': {axis: unit['position'][axis] for axis in ('x', 'y')}}
            for unit in units
        ]
    return {
        'officer_groups': {key: sorted(value) for key, value in sorted(groups.items())},
        'unit_round_pools': sorted(row['id'] for row in structure['unitReinforceRoundPool'] if eligible(row)),
        'maps': maps,
        'constructions': constructions,
    }


def eligible(row):
    return not row['limitedScene'] or 1 in row['limitedScene']


def main():
    build_data.arguments(__doc__)
    result = extract(build_data.container())
    lines = [f'# Build {build_data.build()}, standard versus 1v1. Generated by',
             '# scripts/extract_opening.py; see docs/rules/opening.md.', '']
    for key, value in result.items():
        if isinstance(value, dict):
            lines.append(f'{key}:')
            lines.extend(f'  {identifier}: {json.dumps(row, separators=(", ", ": "))}' for identifier, row in value.items())
        else:
            lines.append(f'{key}: {json.dumps(value)}')
        lines.append('')
    (Path(__file__).resolve().parents[1] / 'config/opening.yaml').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
