#!/usr/bin/env python3
"""Extract build 2259 standard 1v1 reinforcement prediction inputs.

Usage: python scripts/extract_reinforcements.py <ConfigDataContainer.json> <Data/>
Requires UnityPy. Writes config/reinforcements.yaml.
"""
import json
from pathlib import Path
import struct
import sys

from extract_prices import blobs, parse_reinforce_item, read_string, config_numbers
from extract_opening import eligible


def catalogue(blob, kind):
    rows = {}
    for offset in range(0, len(blob) - 4, 4):
        row = parse_reinforce_item(blob, offset)
        if not row or not 100_000 <= row['id'] < 100_000_000:
            continue
        _, cursor = read_string(blob, offset + 4)
        cursor += 4  # isTestData
        for _ in range(4):
            _, cursor = read_string(blob, cursor)
        cursor += 12  # level, scope, supply
        for _ in range(2):
            _, cursor = read_string(blob, cursor)
        cursor += 4  # reactorCore
        count, = struct.unpack_from('<i', blob, cursor)
        cursor += 4 + 4 * count
        early, late, repeated = struct.unpack_from('<3i', blob, cursor)
        rows[row['id']] = dict(row, kind=kind, limitedScene=row['scenes'],
                              earliestRound=early, latestRound=late,
                              canRepeated=bool(repeated))
    return list(rows.values())


def extract(structure, data):
    raw = blobs(data / 'level0', [136, 167, 188])
    rows = catalogue(raw[167], 'skill') + catalogue(raw[188], 'equipment')
    rows.extend(dict(row, kind='officer') for row in structure['officerDatas'])
    cards = {}
    for row in rows:
        if row['scope'] != 1 or not eligible(row):
            continue
        assert row.get('appearCondition', 0) in (0, 1)
        cards[row['id']] = dict(level=row['level'], group=row.get('typeID', 0),
                               earliest=row['earliestRound'], latest=row['latestRound'],
                               repeated=row['canRepeated'],
                               cooldown=row['kind'] == 'skill' and row['level'] == 4,
                               absent_units=row.get('unitID', []) if row.get('appearCondition') == 1 else [])
    units = {}
    for row in structure['unitReinforceDatas']:
        if not eligible(row):
            continue
        assert row['scope'] == 0 and len(set(row['unitID'])) == 1
        units[row['id']] = dict(unit=row['unitID'][0], round=row['activeRound'])
    # decline_supply[i] is what declining the unit offer of rounds[i] pays.
    pools = {row['id']: dict(rounds=row['roundGroup'], decline_supply=row['giveUpSupply'],
                             supply_round=row['supplyRound'],
                             supplies=row['supplyReinforceID'])
             for row in structure['unitReinforceRoundPool'] if eligible(row)}
    weights = {row['round']: [row[f'level{level}'] for level in range(1, 6)]
               for row in structure['reinforceItemProbabilityDatas']}
    prevented = {row['id']: row['unitID'] for row in structure['officerDatas']
                 if row['preventUnitReinforcements'] and eligible(row)}
    unit_costs = {row['id']: dict(supply=row['baseMoney'], unlock=row['unlockPrice'],
                                 tech_step=row['techUpgradeIncreaseSupplyPerCount'],
                                 tech_cap=row['techUpgradeMaxSupplyLimit'])
                  for row in structure['cardDatas']}
    quantity = int(next(row['value'] for row in structure['commonParms']
                        if row['key'] == 'unit_reinforcement_quantity'))
    return dict(ordinary_count=config_numbers(raw[136])['reinforce_item_count'],
                unit_count=quantity, cards=dict(sorted(cards.items())),
                units=dict(sorted(units.items())), pools=pools, weights=weights,
                prevented=prevented, unit_costs=unit_costs)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    structure = json.loads(Path(sys.argv[1]).read_text())['m_Structure']
    inputs = extract(structure, Path(sys.argv[2]))
    lines = ['# Build 1.11.1.3.2259, standard versus 1v1. Generated by',
             '# scripts/extract_reinforcements.py; see docs/rules/reinforcements.md.', '']
    for key, value in inputs.items():
        if isinstance(value, dict):
            lines.append(f'{key}:')
            lines.extend(f'  {identifier}: {json.dumps(row)}' for identifier, row in value.items())
        else:
            lines.append(f'{key}: {value}')
        lines.append('')
    (Path(__file__).resolve().parents[1] / 'config/reinforcements.yaml').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
