#!/usr/bin/env python3
"""Extract what each standard 1v1 map puts on the board into `config/maps.yaml`.

    python3 scripts/extract/extract-maps.py [--build BUILD] [--check]

Read through `scripts/build_data.py`. A map is a `matchSettings` row, one of
`extract_opening.MAPS`, whose `mapData` names a `MapData` of `sharedassets0`;
several rows share one. Its `buildingDatas` are every building the map places,
in the order `FightBuildingLoader.Load` creates them:

* a tower, which a team owns, is created by `FightController.CreateFightTower`
  and is `config/towers.yaml`'s, so here it is only its place in the order and
  where it stands;
* every other building is a neutral `FightCrystal`. When its
  `enablePathfinding` holds, the `FightCrystal` constructor gives it an
  `RVOControllerFixed` whose radius is the row's `radius` and whose collider
  priority is its `pathfindingColliderPriority`. One without runs no
  controller, takes no part in a fight's movement, and is left out.

A position and a radius are the FPoint Q32.32 raw integers the build stores,
because a crystal stands at fractions of a metre. `docs/rules/map.md` states
what a crystal does in a fight.

A map data also names its `MapLayout` (`layoutName`): one `PlayerTerritory`
per seat, each a main region and the regions beside it. A region is a
`MapRegion`: an id, a rectangle in whole world metres (`MapRect`, its least
corner and its size), the way it faces (`Facing`), and the round it opens
(`activeRound`). `docs/rules/map.md` states what the regions are.
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import build_data  # noqa: E402
from extract_opening import MAPS  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "config/maps.yaml"
ONE = 1 << 32
FACINGS = ["forward", "right", "back", "left"]


def raw(value):
    return value["m_rawValue"]


def render(structure):
    settings = {row["id"]: row for row in structure["matchSettings"]}
    missing = [map_id for map_id in MAPS if map_id not in settings]
    if missing:
        raise SystemExit(f"matchSettings holds no row for {missing}")
    lines = [
        "schema: mechcore.maps",
        "",
        "# What each standard 1v1 map puts on the board. Generated by",
        "# scripts/extract/extract-maps.py; docs/rules/map.md states what a",
        "# crystal does in a fight.",
        "",
        "# The map data each map id plays on.",
        "maps:",
    ]
    names = []
    for map_id in MAPS:
        name = settings[map_id]["mapData"]
        lines.append(f"  {map_id}: {name}")
        if name not in names:
            names.append(name)
    lines += [
        "",
        "# The layout each map data lays its territories out by.",
        "layouts:",
    ]
    all_data = build_data.shared("MapData")
    layouts = []
    for name in names:
        if name not in all_data:
            raise SystemExit(f"sharedassets0 holds no MapData {name}")
        layout = all_data[name]["layoutName"]
        lines.append(f"  {name}: {layout}")
        if layout not in layouts:
            layouts.append(layout)
    lines += [
        "",
        "# Each layout's territories, one per seat in seat order: the id of its",
        "# main region, and every region by id with its rectangle in world",
        "# metres (least corner and size), the way it faces and the round it",
        "# opens.",
        "map_layouts:",
    ]
    all_layouts = build_data.shared("MapLayout")
    for layout in layouts:
        if layout not in all_layouts:
            raise SystemExit(f"sharedassets0 holds no MapLayout {layout}")
        lines.append(f"  {layout}:")
        for territory in all_layouts[layout]["playerTerritories"]:
            if territory["useCustomStartPosition"]:
                raise SystemExit(f"{layout} starts a territory at a custom position")
            lines.append(f"    - main_region: {territory['mainRegionID']}")
            lines.append("      regions:")
            for region in territory["regions"]:
                rect = region["bound"]["rect"]
                lines.append(
                    f"        - {{id: {region['id']}, x_min: {rect['m_XMin']}, y_min: {rect['m_YMin']}, "
                    f"width: {rect['m_Width']}, height: {rect['m_Height']}, "
                    f"facing: {FACINGS[region['facing']]}, active_round: {region['activeRound']}}}"
                )
    lines += [
        "",
        "# Each map data's buildings in the order the game creates them: a",
        "# tower, config/towers.yaml's, by team and type and where it stands in",
        "# metres; a neutral crystal that runs an RVO controller by its centre,",
        "# its radius and its collider priority, the first two FPoint raw.",
        "map_data:",
    ]
    for name in names:
        rows = all_data[name]["buildingDatas"]
        if [row["index"] for row in rows] != list(range(len(rows))):
            raise SystemExit(f"{name} does not list its buildings in index order")
        lines.append(f"  {name}:")
        for row in rows:
            x, z = raw(row["position"]["x"]), raw(row["position"]["y"])
            if row["teamType"] >= 0:
                if x % ONE or z % ONE:
                    raise SystemExit(f"{name} places a tower at a fraction of a metre")
                lines.append(
                    f"    - {{kind: tower, team_id: {row['teamType']}, building_type_id: {row['buildingType']}, "
                    f"x: {x // ONE}, z: {z // ONE}}}"
                )
            elif row["enablePathfinding"]:
                lines.append(
                    f"    - {{kind: crystal, x: {x}, z: {z}, radius: {raw(row['radius'])}, "
                    f"collider_priority: {row['pathfindingColliderPriority']}}}"
                )
    return "\n".join(lines) + "\n"


def main():
    arguments = build_data.arguments(__doc__, lambda parser: parser.add_argument("--check", action="store_true"))
    written = render(build_data.container())
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != written:
            print("config/maps.yaml differs from the build's export", file=sys.stderr)
            return 1
        print("config/maps.yaml agrees with the build's export byte for byte")
        return 0
    OUTPUT.write_text(written)
    print(f"maps of build {build_data.build()} -> {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
